export const uid=()=>Math.random().toString(36).slice(2,9);
export const id=(prefix:string,taken:string[])=>{let v=prefix+uid(),i=0;while(taken.indexOf(v)>=0&&i<50){v=prefix+uid();i++}return v};
export const patientId=(taken:string[])=>{let v='YC-1001',i=0;do{v='YC-'+(1001+Math.floor(Math.random()*8998))}while(taken.indexOf(v)>=0&&++i<200);if(taken.indexOf(v)>=0){let n=1001;while(taken.indexOf('YC-'+n)>=0)n++;v='YC-'+n}return v};
export const stamp=()=>new Date().toISOString();
export const MON=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const pad=(n:number)=>String(n).padStart(2,'0');
export const dayKey=(d:Date)=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());
export const today=()=>dayKey(new Date());
export const parseDate=(d?:string)=>{const p=String(d||'').split('-').map(Number);return p[0]&&p[1]?new Date(p[0],p[1]-1,p[2]||1):new Date()};
export const addDays=(d:string,n:number)=>{const v=parseDate(d);return dayKey(new Date(v.getFullYear(),v.getMonth(),v.getDate()+n))};
export const dateLabel=(d?:string)=>{const v=parseDate(d);return v.getDate()+' '+MON[v.getMonth()]+' '+v.getFullYear()};
export const dayLabel=(d?:string)=>{const v=parseDate(d);return v.getDate()+' '+MON[v.getMonth()]};
export const monthLabel=(d?:string)=>{const v=parseDate(d);return MON[v.getMonth()]+' '+v.getFullYear()};
export const weekDay=(d?:string)=>parseDate(d).toLocaleDateString('en-IN',{weekday:'short'});
export const monthKey=(d?:string)=>String(d||'').slice(0,7);
export const monthStart=(d?:string)=>monthKey(d)+'-01';
export const monthEnd=(d?:string)=>{const v=parseDate(d);return dayKey(new Date(v.getFullYear(),v.getMonth()+1,0))};
export const money=(n?:number)=>'\u20B9'+(Number(n)||0).toLocaleString('en-IN');
export const num=(v:unknown,fallback=0)=>{const n=Number(v);return isFinite(n)?n:fallback};
export const isNum=(v:unknown):v is number=>typeof v==='number'&&isFinite(v);
export const isBlank=(v:unknown)=>v==null||(typeof v==='string'&&v.trim()==='');
export const clamp=(v:number,a:number,b:number)=>Math.min(b,Math.max(a,v));
export const initials=(name?:string)=>String(name||'?').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
export const timeLabel=(t?:string)=>{const p=String(t||'').split(':');if(!p[0])return '';const h=Number(p[0]);return isFinite(h)?((h%12||12)+':'+(p[1]||'00')+' '+(h<12?'AM':'PM')):''};
export const timeRange=(a?:string,b?:string)=>[timeLabel(a),timeLabel(b)].filter(Boolean).join(' - ');
export const sortDateDesc=<T,>(list:T[],get:(x:T)=>string)=>list.slice().sort((a,b)=>(get(b)||'').localeCompare(get(a)||''));
export const sortDateAsc=<T,>(list:T[],get:(x:T)=>string)=>list.slice().sort((a,b)=>(get(a)||'').localeCompare(get(b)||''));
export const sumBy=<T,>(list:T[],get:(x:T)=>number)=>list.reduce((s,x)=>s+get(x),0);
export const download=(name:string,content:string,type='application/json')=>{const b=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
